apiVersion: v1
kind: Service
metadata:
  name: blue-svc
  labels:
    name: blue-svc
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    name: blue-deployment
  type: NodePort
  