apiVersion: v1
kind: Service
metadata:
  name: red-svc
  labels:
    name: red-svc
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    #name: red-deployment
    #name: blue-deployment
    name: red-deployment
  type: NodePort
  