---
- name: nginx
  hosts: dev
  become: yes
  tasks:
  - name: install package on os based
    set_fact:
      apache_package: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
    when: ansible_distribution is defined
  - name: Install the service
    package:
      name: "{{ apache_package }}"
      state: present
  - name: create content
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Start and enable apache service
    service:
      name: "{{ apache_package }}"
      state: started
      enabled: yes
  handlers:
    - name: Restart apache
      service:
        name: "{{ apache_package }}"
        state: restarted