# copy the id_rsa.pub to authorized_keys
---
- hosts: docker
  become: yes
  tasks:
    - name: copy id_rsapub to authorized
      shell: cat /home/centos/.ssh/id_rsa.pub  >> /home/centos/.ssh/authorized_keys
      register: copy_id_rsapub_to_authorized
      changed_when: copy_id_rsapub_to_authorized.rc == 0
    - name: check the content
      debug:
        msg: "{{ copy_id_rsapub_to_authorized.stdout }}"
