apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysqlpod
  name: mysqlpod
  namespace: todo
spec:
  containers:
  - image: mysql:5.7
    name: mysqlpod
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: db-cm
      - secretRef:
          name: db-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
