apiVersion: v1
kind: Pod
metadata:
  labels:
    run: phptodo-pod
  name: phptodo-pod
spec:
  containers:
  - image: formycore/phptodo:060403
    name: phptodo-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
