apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pd
      labels:
        app: nginx
    spec:
      containers:
        - name: nginix-container
          image: nginx:latest
          ports:
           - containerPort: 80
          volumeMounts:
            - name: myvolume
              mountPath: /data-nginx
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: my-pvc