apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain # Delete # Recycle
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
