apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  volumes: # volumes are for the pods
    - name: my-volume
      hostPath: 
        path: /var/k8s
  restartPolicy: Never
  containers:
    - name: mybusybox
      image: busybox
      command: ['sh', '-c', 'echo learning k8s with samantha!!! > /aish/k8s.txt && sleep 3600']
      volumeMounts:
        - name: my-volume
          mountPath: /aish