apiVersion: v1
kind: Pod
metadata:
  name: persistance-pod
spec:
  containers:
    - name: persistance-container
      image: nginx
      volumeMounts:
        - name: persistance-pod-storage
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: persistance-pod-storage
      persistentVolumeClaim:
        claimName: demopvc
  nodeName: nodea    