---
- name: Sync Pull task - Executed on  the Destination host "{{groups['app'][1]}}"
  hosts: "{{groups['check'][0]}}"
  user: maanya
  tasks:   
    - name: Copy the file from jenkins to docker using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{groups['check'][1]}}"
      register: syncfile
      run_once: true
      with_items:
       - /home/maanya/intel