apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: todo
    team: integration
    # These labels acts as indentifiers to the pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
        