<<<<<<< HEAD
---
# vars file for default
pack_name: apache2
php_packages: 
  - php
  - php-mysql
info_html_url: https://raw.githubusercontent.com/sandeepmchary/Devops_wordpress_Notes/master/info.php

=======
---
# vars file for default
pack_name: apache2
php_packages: 
  - php
  - php-mysql
info_html_url: https://raw.githubusercontent.com/sandeepmchary/Devops_wordpress_Notes/master/info.php

>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
