apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec: # specify the access modes and capacity
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: "" # we need to discuss , for now just keep empty
