<<<<<<< HEAD
- name: Update repos
  package:
    name: "*"
    state: latest
- name: Install required java
  package:
    name: "{{ required_java }}"
    state: present
- name: Setting default java
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/{{ set_java }}/bin/java
=======
- name: Update repos
  package:
    name: "*"
    state: latest
- name: Install required java
  package:
    name: "{{ required_java }}"
    state: present
- name: Setting default java
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/{{ set_java }}/bin/java
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
