# kubectl api-resource | grep < name of the deployment or svc or pod >
# kubectl api-resource | grep pod
apiVersion: v1 # we can get this with above command
kind: Pod # this is kind of the manifest we are working on
metadata: # metadata for the pod
  name: vote # name of the pod
  labels: # with this only we can identify the pod
    app: python # any key value here we have given as app:python
    role: vote # any key value here we have given as role: vote
    version: v1 # any key value here we have given as version: v1
spec: # spec for the containers
  containers: # containers manifest
    - name: app # name of the app
      image: schoolofdevops/vote:v1 # image 
      ports: # 
        - containerPort: 80 # port for the container
          protocol: TCP 
