apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-web
  name: mongo-web
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: webapp
  type: NodePort