apiVersion: apps/v1
kind: Deployment
metadata:
  Name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd-frontend
  template:
    metadata:
      labels:
        name: httpd-frontend
  spec:
    containers:
    - name: httpd-frontend
      image: httpd:2.4-alpine
kubectl create -f deployment-definition-httpd.yaml