apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    team: integration
    app: todo
spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
        - containerPort: 80
