<<<<<<< HEAD
---
- hosts: tomcat
  become: yes
  tasks:
  - name: Install tomcat
    package:
      name: tomcat
      state: present
  - name: Install additional packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - tomcat-webapps
      - tomcat-admin-webapps
  - name: Start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
  - name: configure tomcat user-management
    copy:
      src: tomcat_users.xml
      dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: restart tomcat
    service:
      name: tomcat
      state: restarted
=======
---
- hosts: tomcat
  become: yes
  tasks:
  - name: Install tomcat
    package:
      name: tomcat
      state: present
  - name: Install additional packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - tomcat-webapps
      - tomcat-admin-webapps
  - name: Start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
  - name: configure tomcat user-management
    copy:
      src: tomcat_users.xml
      dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: restart tomcat
    service:
      name: tomcat
      state: restarted
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
      