apiVersion: v1
kind: ReplicationController
metadata:
  name: samantharc
spec:
  replicas: 3
  selector:
    team: dev
  template:
    metadata:
      labels:
        team: dev
    spec:
      containers:
      - name: samanthacont
        image: nginx:1.7.1
        ports:
        - containerPort: 80
        