<<<<<<< HEAD
---
# tasks file for jenkins
- name: Downlaod Jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
- name: Jenkins rpm 
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
- name: Install Jenkins
  package:
    name: jenkins
    state: present
- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true
- name: Sleep for 30 seconds and Continue play
  wait_for: timeout=30
  delegate_to: localhost
- name: init passwd jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: result
- name: Print init password
  debug:
    var: result.stdout                    
=======
---
# tasks file for jenkins
- name: Downlaod Jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
- name: Jenkins rpm 
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
- name: Install Jenkins
  package:
    name: jenkins
    state: present
- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true
- name: Sleep for 30 seconds and Continue play
  wait_for: timeout=30
  delegate_to: localhost
- name: init passwd jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: result
- name: Print init password
  debug:
    var: result.stdout                    
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
