<<<<<<< HEAD
---
- hosts: all
  become: yes
  tasks:
    - name : Ensure the HTTPD package is installed
      yum:
        name: httpd
        state: present
    - name : HTTPD Service
      service:
        name: httpd
        state: restarted
=======
---
- hosts: all
  become: yes
  tasks:
    - name : Ensure the HTTPD package is installed
      yum:
        name: httpd
        state: present
    - name : HTTPD Service
      service:
        name: httpd
        state: restarted
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
        enabled: yes