<<<<<<< HEAD
---
- hosts: all
  become : yes
  tasks:
    - name : MOTD
      template:
        src: motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
=======
---
- hosts: all
  become : yes
  tasks:
    - name : MOTD
      template:
        src: motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
        