<<<<<<< HEAD
---
- hosts: all
  become: yes
  tasks:
    - name : Ensure user exists
      user:
        name : "{{ item }}"
        with_items:
        - "{{ users }}"
    - name: Ensure folder exists
      file:
        path: '/home/{{ item.0}}/{{item.1}}'
        state: directory
=======
---
- hosts: all
  become: yes
  tasks:
    - name : Ensure user exists
      user:
        name : "{{ item }}"
        with_items:
        - "{{ users }}"
    - name: Ensure folder exists
      file:
        path: '/home/{{ item.0}}/{{item.1}}'
        state: directory
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
      with_