pipeline 
{
    agent any
tools {
  maven 'maven'
}

    stages
    {
        stage('Scm Checkout')
        {
            steps
            {
                git 'https://github.com/formycore/valaxy.git'
                sh 'mvn clean install'
                sh '''
                ifconfig -a
                '''
            }
        }
    }
}