apiVersion: v1
kind: Service
metadata:
  name: dellvalaxy
  labels:
    name: valaxy
spec:
  selector:
    app: dellvalaxy
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200

