apiVersion: v1
kind: Service
metadata:
  name: rollingupdate-svc
  labels:
    name: rollingupdate-svc
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
      name: rollingupdate-demo
  type: NodePort
