# example for source ~/bashrc with ansible
---
- hosts: localhost
  tasks:
    - name: Source bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
      register: bashrc
    - debug: 
        msg: "{bashrc.stdout_lines}"
