<<<<<<< HEAD
---
- hosts: tomcat
  become: yes
  tasks:
  - name: install tomcat
    package:
      name: tomcat
      update_cache: yes
      state: present
=======
---
- hosts: tomcat
  become: yes
  tasks:
  - name: install tomcat
    package:
      name: tomcat
      update_cache: yes
      state: present
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
