version: '3'
services:
  backend:
    image: flaskapp:v1
    ports:
    - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root 
      MYSQL_PASSWORD: admin
      MYSQL_DB: mydb
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
  


      
