<<<<<<< HEAD
---
- hosts: all
  become: yes
  tasks:
    - include: jenkins.yml
      when: ansible_os_family == "Redhat"
    - include: ubujenkins.yml
      when: ansible_os_family == "Debian"
=======
---
- hosts: all
  become: yes
  tasks:
    - include: jenkins.yml
      when: ansible_os_family == "Redhat"
    - include: ubujenkins.yml
      when: ansible_os_family == "Debian"
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
