apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: voters
spec:
  replicas: 3
  minReadySeconds: 10
  selector: # in the selectors we can choose matchLabels or matchExpress 
  # matchExpressions are in replicationset 
    matchLabels:
      role: vote
    matchExpressions:
      - {key: version, operator: In, values: [v1,v2,v3]}
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v1
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote:v1
          ports:
            - containerPort: 80
              protocol: TCP

