---
- name : Install docker
  hosts: localhost
  become: true
  tasks:
    - name: set mydistrubution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"
      register: mydistribution_output
    - debug:
        var: mydistribution_output
    - name: Set up the repository
      package:
        name: yum-utils
        state: present
    - name: Add Sigining key
      ansible.builtin.rpm_key:
        key: "https://"