apiVersion: v1
kind: Service
metadata:
  name: recreate-demo
  labels:
    name: recreate-demo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    name: recreate-demo
  type: NodePort
  