apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-demo
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: recreate-demo
  template:
    metadata:
      labels:
        name: recreate-demo
    spec:
      containers:
        - name: recreate-demo
          image: adamtravis/rollouts:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
