<<<<<<< HEAD
apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
        - name: simple-pod
          image: nginx
          ports:
            - containerPort: 80
=======
apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
        - name: simple-pod
          image: nginx
          ports:
            - containerPort: 80
>>>>>>> 9fe199743c6df19ba1530059bc0dd794606c74e5
