---
- name: Example on handlers
  hosts: test
  become: yes
  tasks:
    - name: Install nginx 
      package:
        name: nginx
        state: present
        update_cache: true
    - name: Index html copy
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      notify:
        - Restart nginx
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

